version: "3.9"

services:
  devopsdb:
    image: joyboyluffycoder/automation:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
    volumes:
      db:/docker-entrypoint-initdb.d/db_backup.sql
    networks:
      - mynetwork

  application:
    image: joyboyluffycoder/automation:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    volumes:
      app:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
volumes:
  app:
  db:
